# badge: https://github.com/matze/pkgconfig/workflows/CI/badge.svg?branch=master

name: CI

on:
  push:
    branches: [ master ]
    paths:
    - '**.py'
    - '**.pc'
    - '**.yml'
    - '**.toml'
    - '**.cfg'
    - '**.ini'
  pull_request:
    branches: [ master ]
    paths:
    - '**.py'
    - '**.pc'
    - '**.yml'
    - '**.toml'
    - '**.cfg'
    - '**.ini'

jobs:
  linux:

    strategy:
      fail-fast: true
      matrix:
        include:
            - os: ubuntu-20.04
              python-version: '3.9'
              toxenv: py39
            - os: ubuntu-22.04
              python-version: '3.10'
              toxenv: py310
            - os: ubuntu-22.04
              python-version: '3.11'
              toxenv: py311
            - os: ubuntu-24.04
              python-version: '3.12'
              toxenv: py312

    env:
      TOXENV: ${{ matrix.toxenv }}

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Linux packages
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config
    - name: Install Python requirements
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Install pkgconfig
      run: pip install -ve .
    - name: run tox env
      run: tox --skip-missing-interpreters

  macOS:

    needs: linux
    strategy:
      fail-fast: true
      matrix:
        include:
            - os: macos-14
              python-version: '3.11'
              toxenv: py311

    env:
      TOXENV: ${{ matrix.toxenv }}

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install macOS packages
      run: |
        brew install pkg-config || brew upgrade pkg-config
    - name: Install Python requirements
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Install pkgconfig
      run: pip install -ve .
    - name: run tox env
      run: tox --skip-missing-interpreters
